build:
  version: 1.0
accounts:
  message: "Welcome to AaronyBank accounts related Prod APIs "
  contactDetails:
    name: "Aaron Huang - Prod Developer"
    email: "aaron@neux.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345