build:
  version: 3.0
accounts:
  message: "Welcome to AaronyBank accounts related local APIs "
  contactDetails:
    name: "Aaron Huang - Developer"
    email: "aaron@neux.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345