build:
  version: "3.0"

cards:
  message: "Welcome to AaronBank cards related local APIs "
  contactDetails:
    name: "Aaron Huang - Developer"
    email: "Aaron@neux.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932