build:
  version: "1.0"

loans:
  message: "Welcome to AaronBank loans related Prod APIs "
  contactDetails:
    name: "Aaron Huang - Prod Developer"
    email: "Aaron@neux.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934