build:
  version: "2.0"

loans:
  message: "Welcome to AaronBank loans related QA APIs "
  contactDetails:
    name: "Aaron Huang - QA Developer"
    email: "Aaron@neux.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934