build:
  version: "3.0"

loans:
  message: "Welcome to AaronBank loans related local APIs "
  contactDetails:
    name: "Aaron Huang - Developer"
    email: "Aaron@neux.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934