spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

# 透過這個設定，我們讓Springboot框架能夠看到並記錄所有在com套件下的日誌語句。這正是我們想要透過這個屬性達成的目標。當
# 這些日誌來自com.neux.gatewayserver套件，且為debug級別時，系統會將它們全部列印出來。
logging:
  level:
    com:
      neux:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # 監控請求數量
      permittedNumberOfCallsInHalfOpenState: 2 # 半開啟狀態允許呼叫數
      failureRateThreshold: 50 # 失敗率閾值
      waitDurationInOpenState: 10000 # 開啟狀態等待時間：10秒